spring:
  jpa:
    properties:
      hibernate:
        event:
          marge:
            entity_copy_observer: allow
        jdbc:
          time_zone: UTC
        ddl-auto: create-drop
  cloud:
    config:
      enabled: false
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

logging:
  level:
    com.as.addressservice: DEBUG
api:
  server:
    dev:
      url: http://localhost:8081
      name: DEV

    prod:
      url: http://localhost:8081
      name: PROD